# Site settings
title: USB104 A7 Notes
description: Notes on the USB104 A7 development board
baseurl: /usb104-a7-notes
url: https://pavel-demin.github.io
permalink: /:slug/

source-link: https://github.com/pavel-demin/usb104-a7-notes
issues-link: https://github.com/pavel-demin/usb104-a7-notes/issues

release-file: https://github.com/pavel-demin/usb104-a7-notes/releases/download/20230322/usb104-a7-notes-20230322.zip

# Build settings
markdown: kramdown
highlighter: rouge
